% Trialling alternative method for loading and manipulating variables for Simulink Simplified Model

SELECT.blah = 'normal';

switch SELECT.wind_turbine
    case "SWT-2.3-93"
        SELECT.control_settings = fullfile('SWT_2_3_93', 'power_ddkW_SWT_reos_02_HR2_grid.mat');    % iter2 - reos_02_HR2
    case "SWT-2.3-101"

    case "GE-2.5-100"
        % SELECT.control_settings = fullfile('GE_2p5-100', 'speed_power_lut_oem_mod_v1_ge2p5.mat');

end

SELECT.HydraulicCycling = 'On';
% SELECT.HydraulicCycling = 'Off';

% ==================================================
% Select if Pitch System requires Hydraulic Cycling
% ==================================================

SELECT.Quantization = 'Off';
% SELECT.Quantization = 'REOS';
% SELECT.Quantization = 'NWT';

% ===================================
% Select Estimator (or off for SCADA)
% ===================================

% SELECT.Uestimator = 'Siemens';
% SELECT.Uestimator = 'Paper';
SELECT.Uestimator = 'SCADA';

% =========================================
% Rotor selection FOR WIND SPEED ESTIMATION
% =========================================

SELECT.rotor_input_file_wind_speed_estim = 'SWT2_3_B45_Anakata_v5_UP1_Clean_Cp.mat';  % New bEst match for ORSTED data';

%% Model and Subsystem Version

% ========================================
%             INSTRUCTIONS
%             ------------
% The purpose of this subsection is to select
% the apprripriate wrapper model, and the
% appropriate VERSION for each subsystem.

% First, load the wrapper model. Then,
% run the Load_Latest_Subsystem_Version
% function to load the default subsys versions.

% To overwrite a version, for example if
% developing a new subsys, just add it after
% the Load_Latest_Subsystem_Version function
% is called.
% ========================================

% ==========================
% Select Base Simulink model
% ==========================

if strcmpi(SELECT.Plant, 'EXTERNAL')
    SELECT.Simulink_model = 'External_Wrapper_v01';
else
    SELECT.Simulink_model = 'Simulator_v01';

end

% =======================
% Load Default Subsystems
% =======================

SELECT = reos.subsys_library.Load_Latest_Subsystem_Version(SELECT);

%% Directories and Files

% Directory where the current new scripts are located:
Dir_scripts = fullfile (Dir_parent, 'generic');
cd(Dir_scripts)

% Directory where many of JP's functions live
Dir_Torque_Internal = fullfile(reos_shared_nextcloud_dir(), 'Projects', 'INTERNAL--torque_ctr_scig');
addpath(Dir_Torque_Internal)

% TODO: Move all above Projects Folder scripts into the Git

% Directory for Rotor Input files
Dir_rotors = fullfile (Dir_Torque_Internal, 'rotor_input');

% Directory for autogenerated "stop function" reports
Dir_tests = fullfile (Dir_Torque_Internal, 'log', log_file);

% File for idealised turbine characteristics
File_idealised_tables = fullfile (Dir_Torque_Internal, 'ctr_input', SELECT.idealised_tables);

% File for Control Input
File_control_settings = fullfile (Dir_Torque_Internal, 'ctr_input', SELECT.control_settings);

% Base model
File_Simulink_Model = fullfile (Dir_parent, 'generic', 'Model', 'Base_model', string(SELECT.Simulink_model+".slx"));

%% Simulation specific

ss = reos.wtsim.Simulation_setup();

%% Obtain p struct

p = reos.wtsim.Load_sim_parameters(ss, SELECT, simpar.windCase, Dir_rotors, File_idealised_tables, File_control_settings);

% Plot pitch curve (sense check)
figure(99);
plot(p.pit.PitchTablePowerGrid, p.pit.PitchTableAngle_LOW(p.pit.pitch1, p.pit.pitch2, p.pit.pitch3, p.pit.pitch4, p.pit.pitch5), '-*', LineWidth=2);
plot(p.pit.PitchTablePowerGrid, p.pit.PitchTableAngle_UP(p.pit.pitch1,p.pit.pitch2,p.pit.pitch3,p.pit.pitch4,p.pit.pitch5), '-*', LineWidth=2);
plot(p.pit.PitchTablePowerGrid, p.pit.PitchTableAngle(p.pit.pitch1, p.pit.pitch2, p.pit.pitch3, p.pit.pitch4, p.pit.pitch5), '-*', LineWidth=2);


%% Load SCADA

simvars = reos.wtsim.Load_SCADA(Dir_Torque_Internal, simpar.windCase, SELECT.Anenometer, p.gen.base.gearRatio, []);

% figure(1)
% plot(simvars.DateTime,simvars.U_hub,'.-')
% grid on
% grid minor
% ylabel('Wind [m/s]')
% xlabel('Time')
% title(string(simpar.windCase)+'__')


[out_data, SELECT] = reos.batch_sim.run_sim_lib(ss, SELECT, p, simvars);

% return

%% Preparations for stop function


